### ISSUE TITLE
Vizualizacion de datos

### ISSUE THREAD

**Issue by EdgarExa** [SistemasTecTlaxiaco/actividad-11-practica-de-visualizacion-de-datos-turbandaxd#1]
[ReporteDe_Vizualizaciondedatos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-11-practica-de-visualizacion-de-datos-turbandaxd/files/15488601/ReporteDe_Vizualizaciondedatos.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
